### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by Fortunate-MAN**
Fixed some typos

### CODE REVIEW

**Comment by Bhargav-Rao** [comment]
Hey but those were possibile typos 😆

**Comment by Fortunate-MAN** [comment]
Don't merge now, fixing some more typos..

**Comment by Bhargav-Rao** [comment]
Don't worry, Both @Tunaki and @jdd-software are busy this week.

**Comment by Fortunate-MAN** [comment]
There are typos in the code also, the same ones but won't edit that right now.

**Pull request merged**
